### ISSUE TITLE
tp5 无法引入

### ISSUE THREAD

**Issue by xialamp** [bumoproject/bumo-sdk-php#1]
composer 安装成功，在tp5 里面无法引入,貌似是autoload 写得有问题

**Comment by frm430342210** [comment]
请问报了什么错呢？

**Comment by frm430342210** [comment]
> composer 安装成功，在tp5 里面无法引入,貌似是autoload 写得有问题

请问报了什么错呢？我们测试是没问题的.

**Comment by xialamp** [comment]
not found

**Comment by frm430342210** [comment]
> not found
> ![image](https://user-images.githubusercontent.com/30463120/53476756-1d314700-3aae-11e9-9ac7-738b062014b5.png)

请看一下我们的示例是如何使用的，谢谢！

**Comment by frm430342210** [comment]
![image](https://user-images.githubusercontent.com/18002052/53478865-c7ab6900-3ab2-11e9-9a2c-05eb83643448.png)

**Comment by frm430342210** [comment]
https://github.com/bumoproject/bumo-sdk-php/issues/1#issuecomment-467770983

**Comment by frm430342210** [comment]
> > composer 安装成功，在tp5 里面无法引入,貌似是autoload 写得有问题
> 
> 请问报了什么错呢？我们测试是没问题的.

![image](https://user-images.githubusercontent.com/18002052/53478928-ef023600-3ab2-11e9-8782-14bb68fe5bed.png)
