### ISSUE TITLE
创建账号undefined function src\crypto\key\ed25519_publickey()

### ISSUE THREAD

**Issue by asciiadmin** [bumoproject/bumo-sdk-php#2]
![default](https://user-images.githubusercontent.com/48049857/53493559-8d53c300-3ad6-11e9-8e37-2a2f6e6ca73f.png)

**Comment by frm430342210** [comment]
没有配置ed25519的库

**Comment by frm430342210** [comment]
![image](https://user-images.githubusercontent.com/18002052/53494815-8c706080-3ad9-11e9-9ba6-d516c5e96ff0.png)

那是因为缺少ed25519的库，请按说明配置。
将libs目录下的对应版本的ed25519拷贝到php的扩展目录下，才能够正常使用。

**Comment by frm430342210** [comment]
还需要在php.ini配置文件中添加“extension=ed25519.so”
