### ISSUE TITLE
php-sdk无法使用

### ISSUE THREAD

**Issue by ling5464** [bumoproject/bumo-sdk-php#3]
安装.so 扩展文件 失败
![image](https://user-images.githubusercontent.com/46123467/53730376-b5666c00-3eb2-11e9-8c3c-5dbed28c0e86.png)

**Comment by frm430342210** [comment]
![image](https://user-images.githubusercontent.com/18002052/53776302-9e665f00-3f30-11e9-8c2f-77246cf5080d.png)

你好，在github首页有介绍，请详细阅读。

在libs目录下有一个ed25519.zip压缩包，里面包含了对应php各个版本的ed25519.so的库，将其拷贝到php的扩展目录，并在php.ini中添加“extension=ed25519.so”就可以了。
